apiVersion: v1
kind: ConfigMap
metadata:
  name: hmc-system-namespace-config
  # namespace: default
data:
  namespace.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: hmc-system
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ include "cluster.name" . }}
spec:
  clusterSelector:
    matchLabels:
      helm.toolkit.fluxcd.io/name: {{ include "cluster.name" . }}
      cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
  resources:
    - kind: ConfigMap
      name: hmc-system-namespace-config
  strategy: Reconcile
