apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: wali-dev-1
  namespace: kcm-system
spec:
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    controlPlane:
      amiID: ami-0eb9fdcf0d07bd5ef
      # amiID: ami-0e54671bdf3c8ed8d
      instanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: true
    region: ca-central-1
    # region: eu-central-1
    worker:
      amiID: ami-0eb9fdcf0d07bd5ef
      # amiID: ami-0e54671bdf3c8ed8d
      instanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.small
    workersNumber: 1
  credential: aws-cluster-identity-cred
  serviceSpec:
    services:
      - template: kyverno-3-2-6
        name: kyverno
        namespace: kyverno
        # valuesFrom:
        #   - kind: Secret
        #     name: my-creds
        #     namespace: testns1
    templateResourceRefs:
      - resource:
          apiVersion: v1
          kind: Secret
          name: my-creds
          namespace: kcm-system
        identifier: MyCreds
    priority: 100
    syncMode: Continuous
  template: aws-standalone-cp-0-0-7