apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterSummary
metadata:
  creationTimestamp: "2024-12-28T23:39:58Z"
  finalizers:
  - clustersummaryfinalizer.projectsveltos.io
  generation: 2
  labels:
    hmc.mirantis.com/managed: "true"
    projectsveltos.io/cluster-name: wali-dev-1
    projectsveltos.io/cluster-type: Capi
    projectsveltos.io/profile-name: wali-dev-1
  name: p--wali-dev-1-capi-wali-dev-1
  namespace: hmc-system
  ownerReferences:
  - apiVersion: config.projectsveltos.io/v1beta1
    kind: Profile
    name: wali-dev-1
    uid: e85ac8c6-f12d-4243-9519-00ec7fefcf2e
  resourceVersion: "9895"
  uid: 090faa38-7856-4aae-96ea-aeea7b917a39
spec:
  clusterName: wali-dev-1
  clusterNamespace: hmc-system
  clusterProfileSpec:
    clusterSelector:
      matchLabels:
        helm.toolkit.fluxcd.io/name: wali-dev-1
        helm.toolkit.fluxcd.io/namespace: hmc-system
    continueOnConflict: true
    helmCharts:
    - chartName: ingress-nginx
      chartVersion: 4.11.0
      helmChartAction: Install
      registryCredentialsConfig:
        plainHTTP: true
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      repositoryName: ingress-nginx
      repositoryURL: oci://hmc-local-registry:5000/charts
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: ContinuousWithDriftDetection
    tier: 2147483547
  clusterType: Capi
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    hash: 4lc+actPU2DXVxmyCFYkExx6R+ovlL7xqb6ljXXM5nI=
    lastAppliedTime: "2024-12-28T23:49:45Z"
    status: Provisioned
  helmReleaseSummaries:
  - releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    status: Managing
    valuesHash: Eq4yyx7ALQHto1gbEnwf7jsNxTVy7WuvI5choD2C4SY=
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterSummary
metadata:
  creationTimestamp: "2024-12-28T23:39:58Z"
  finalizers:
  - clustersummaryfinalizer.projectsveltos.io
  generation: 2
  labels:
    hmc.mirantis.com/managed: "true"
    projectsveltos.io/cluster-name: wali-dev-1
    projectsveltos.io/cluster-type: Capi
    projectsveltos.io/profile-name: wali-dev-1
  name: p--wali-dev-1-capi-wali-dev-1
  namespace: hmc-system
  ownerReferences:
  - apiVersion: config.projectsveltos.io/v1beta1
    kind: Profile
    name: wali-dev-1
    uid: e85ac8c6-f12d-4243-9519-00ec7fefcf2e
  resourceVersion: "17132"
  uid: 090faa38-7856-4aae-96ea-aeea7b917a39
spec:
  clusterName: wali-dev-1
  clusterNamespace: hmc-system
  clusterProfileSpec:
    clusterSelector:
      matchLabels:
        helm.toolkit.fluxcd.io/name: wali-dev-1
        helm.toolkit.fluxcd.io/namespace: hmc-system
    continueOnConflict: true
    helmCharts:
    - chartName: ingress-nginx
      chartVersion: 4.11.0
      helmChartAction: Install
      registryCredentialsConfig:
        plainHTTP: true
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      repositoryName: ingress-nginx
      repositoryURL: oci://hmc-local-registry:5000/charts
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: ContinuousWithDriftDetection
    tier: 2147483547
  clusterType: Capi
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    lastAppliedTime: "2024-12-28T23:49:45Z"
    status: Provisioning
  helmReleaseSummaries:
  - releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    status: Managing
    valuesHash: Eq4yyx7ALQHto1gbEnwf7jsNxTVy7WuvI5choD2C4SY=
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterSummary
metadata:
  creationTimestamp: "2024-12-28T23:39:58Z"
  finalizers:
  - clustersummaryfinalizer.projectsveltos.io
  generation: 2
  labels:
    hmc.mirantis.com/managed: "true"
    projectsveltos.io/cluster-name: wali-dev-1
    projectsveltos.io/cluster-type: Capi
    projectsveltos.io/profile-name: wali-dev-1
  name: p--wali-dev-1-capi-wali-dev-1
  namespace: hmc-system
  ownerReferences:
  - apiVersion: config.projectsveltos.io/v1beta1
    kind: Profile
    name: wali-dev-1
    uid: e85ac8c6-f12d-4243-9519-00ec7fefcf2e
  resourceVersion: "17133"
  uid: 090faa38-7856-4aae-96ea-aeea7b917a39
spec:
  clusterName: wali-dev-1
  clusterNamespace: hmc-system
  clusterProfileSpec:
    clusterSelector:
      matchLabels:
        helm.toolkit.fluxcd.io/name: wali-dev-1
        helm.toolkit.fluxcd.io/namespace: hmc-system
    continueOnConflict: true
    helmCharts:
    - chartName: ingress-nginx
      chartVersion: 4.11.0
      helmChartAction: Install
      registryCredentialsConfig:
        plainHTTP: true
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      repositoryName: ingress-nginx
      repositoryURL: oci://hmc-local-registry:5000/charts
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: ContinuousWithDriftDetection
    tier: 2147483547
  clusterType: Capi
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    hash: 4lc+actPU2DXVxmyCFYkExx6R+ovlL7xqb6ljXXM5nI=
    lastAppliedTime: "2024-12-29T00:17:47Z"
    status: Provisioning
  helmReleaseSummaries:
  - releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    status: Managing
    valuesHash: Eq4yyx7ALQHto1gbEnwf7jsNxTVy7WuvI5choD2C4SY=
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterSummary
metadata:
  creationTimestamp: "2024-12-28T23:39:58Z"
  finalizers:
  - clustersummaryfinalizer.projectsveltos.io
  generation: 2
  labels:
    hmc.mirantis.com/managed: "true"
    projectsveltos.io/cluster-name: wali-dev-1
    projectsveltos.io/cluster-type: Capi
    projectsveltos.io/profile-name: wali-dev-1
  name: p--wali-dev-1-capi-wali-dev-1
  namespace: hmc-system
  ownerReferences:
  - apiVersion: config.projectsveltos.io/v1beta1
    kind: Profile
    name: wali-dev-1
    uid: e85ac8c6-f12d-4243-9519-00ec7fefcf2e
  resourceVersion: "17211"
  uid: 090faa38-7856-4aae-96ea-aeea7b917a39
spec:
  clusterName: wali-dev-1
  clusterNamespace: hmc-system
  clusterProfileSpec:
    clusterSelector:
      matchLabels:
        helm.toolkit.fluxcd.io/name: wali-dev-1
        helm.toolkit.fluxcd.io/namespace: hmc-system
    continueOnConflict: true
    helmCharts:
    - chartName: ingress-nginx
      chartVersion: 4.11.0
      helmChartAction: Install
      registryCredentialsConfig:
        plainHTTP: true
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      repositoryName: ingress-nginx
      repositoryURL: oci://hmc-local-registry:5000/charts
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: ContinuousWithDriftDetection
    tier: 2147483547
  clusterType: Capi
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    hash: 4lc+actPU2DXVxmyCFYkExx6R+ovlL7xqb6ljXXM5nI=
    lastAppliedTime: "2024-12-29T00:17:57Z"
    status: Provisioning
  helmReleaseSummaries:
  - releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    status: Managing
    valuesHash: Eq4yyx7ALQHto1gbEnwf7jsNxTVy7WuvI5choD2C4SY=
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterSummary
metadata:
  creationTimestamp: "2024-12-28T23:39:58Z"
  finalizers:
  - clustersummaryfinalizer.projectsveltos.io
  generation: 2
  labels:
    hmc.mirantis.com/managed: "true"
    projectsveltos.io/cluster-name: wali-dev-1
    projectsveltos.io/cluster-type: Capi
    projectsveltos.io/profile-name: wali-dev-1
  name: p--wali-dev-1-capi-wali-dev-1
  namespace: hmc-system
  ownerReferences:
  - apiVersion: config.projectsveltos.io/v1beta1
    kind: Profile
    name: wali-dev-1
    uid: e85ac8c6-f12d-4243-9519-00ec7fefcf2e
  resourceVersion: "17288"
  uid: 090faa38-7856-4aae-96ea-aeea7b917a39
spec:
  clusterName: wali-dev-1
  clusterNamespace: hmc-system
  clusterProfileSpec:
    clusterSelector:
      matchLabels:
        helm.toolkit.fluxcd.io/name: wali-dev-1
        helm.toolkit.fluxcd.io/namespace: hmc-system
    continueOnConflict: true
    helmCharts:
    - chartName: ingress-nginx
      chartVersion: 4.11.0
      helmChartAction: Install
      registryCredentialsConfig:
        plainHTTP: true
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      repositoryName: ingress-nginx
      repositoryURL: oci://hmc-local-registry:5000/charts
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: ContinuousWithDriftDetection
    tier: 2147483547
  clusterType: Capi
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    hash: 4lc+actPU2DXVxmyCFYkExx6R+ovlL7xqb6ljXXM5nI=
    lastAppliedTime: "2024-12-29T00:18:07Z"
    status: Provisioned
  helmReleaseSummaries:
  - releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    status: Managing
    valuesHash: Eq4yyx7ALQHto1gbEnwf7jsNxTVy7WuvI5choD2C4SY=
