apiVersion: v2
name: kyverno
description: A Helm chart to refer the official kyverno helm chart
type: application
version: 3.2.6
appVersion: "v1.12.5"
dependencies:
  - name: kyverno
    version: 3.2.6
    repository: https://kyverno.github.io/kyverno/
