projectsveltos:
  accessManager:
    manager:
      image:
        repository: docker.io/projectsveltos/access-manager
  addonController:
    controller:
      image:
        repository: docker.io/projectsveltos/addon-controller
  classifierManager:
    manager:
      image:
        repository: docker.io/projectsveltos/classifier
  conversionWebhook:
    sveltosWebhook:
      image:
        repository: docker.io/projectsveltos/webhook-conversion
  eventManager:
    manager:
      image:
        repository: docker.io/projectsveltos/event-manager
  hcManager:
    manager:
      image:
        repository: docker.io/projectsveltos/healthcheck-manager
  registerMgmtClusterJob:
    registerMgmtCluster:
      image:
        repository: docker.io/projectsveltos/register-mgmt-cluster
  scManager:
    manager:
      image:
        repository: docker.io/projectsveltos/sveltoscluster-manager
  shardController:
    manager:
      image:
        repository: docker.io/projectsveltos/shard-controller
