apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-clusters-editor-role
rules:
  - apiGroups:
      - hmc.mirantis.com
    resources:
      - managedclusters
    verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
  - apiGroups:
      - hmc.mirantis.com
    resources:
      - multiclusterservices
    verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
