apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-profile-editor-role
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: addon-controller
    app.kubernetes.io/part-of: addon-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
rules:
- apiGroups:
  - config.projectsveltos.io
  resources:
  - profiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.projectsveltos.io
  resources:
  - profiles/status
  verbs:
  - get