{{ if .Values.agent.managementCluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: classifier-rolebinding-sveltos-agent-in-mgmt-cluster
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'classifier-role-sveltos-agent-in-mgmt-cluster'
subjects:
- kind: ServiceAccount
  name: 'classifier-manager'
  namespace: '{{ .Release.Namespace }}'
{{ end }}
