{{ if .Values.agent.managementCluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: classifier-role-sveltos-agent-in-mgmt-cluster
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
{{ end }}
