apiVersion: lib.projectsveltos.io/v1beta1
kind: Classifier
metadata:
  name: default-classifier
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": "hook-failed"
spec:
  classifierLabels:
  - key: sveltos-agent
    value: present
