apiVersion: v1
kind: ServiceAccount
metadata:
  name: addon-controller
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-controller
  labels:
    control-plane: addon-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.addonController.replicas }}
  selector:
    matchLabels:
      control-plane: addon-controller
    {{- include "projectsveltos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: addon-controller
      {{- include "projectsveltos.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: controller
    spec:
      {{- with .Values.addonController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.addonController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
{{ if .Values.agent.managementCluster }}      
      - args: {{- toYaml .Values.addonController.controller.argsAgentMgmtCluster | nindent 8 }}
{{ else }}
      - args: {{- toYaml .Values.addonController.controller.args | nindent 8 }}
{{ end }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.addonController.controller.image.repository }}:{{ .Values.addonController.controller.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: controller
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.addonController.controller.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.addonController.controller.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        runAsNonRoot: true
      serviceAccountName: addon-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: tmp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-manager
  labels:
    control-plane: access-manager
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.accessManager.replicas }}
  selector:
    matchLabels:
      control-plane: access-manager
    {{- include "projectsveltos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: access-manager
      {{- include "projectsveltos.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.accessManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accessManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args: {{- toYaml .Values.accessManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.accessManager.manager.image.repository }}:{{ .Values.accessManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.accessManager.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.accessManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: access-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sc-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-manager
  labels:
    control-plane: sc-manager
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scManager.replicas }}
  selector:
    matchLabels:
      control-plane: sc-manager
    {{- include "projectsveltos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: sc-manager
      {{- include "projectsveltos.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.scManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args: {{- toYaml .Values.scManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.scManager.manager.image.repository }}:{{ .Values.scManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.scManager.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.scManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: sc-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hc-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-manager
  labels:
    control-plane: hc-manager
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.hcManager.replicas }}
  selector:
    matchLabels:
      control-plane: hc-manager
    {{- include "projectsveltos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: hc-manager
      {{- include "projectsveltos.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.hcManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hcManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args: {{- toYaml .Values.hcManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.hcManager.manager.image.repository }}:{{ .Values.hcManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.hcManager.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.hcManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: hc-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-manager
  labels:
    control-plane: event-manager
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.eventManager.replicas }}
  selector:
    matchLabels:
      control-plane: event-manager
    {{- include "projectsveltos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: event-manager
      {{- include "projectsveltos.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.eventManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args: {{- toYaml .Values.eventManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.eventManager.manager.image.repository }}:{{ .Values.eventManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.eventManager.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.eventManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: event-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: classifier-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier-manager
  labels:
    control-plane: classifier
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.classifierManager.replicas }}
  selector:
    matchLabels:
      control-plane: classifier
    {{- include "projectsveltos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: classifier
      {{- include "projectsveltos.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.classifierManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.classifierManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
{{ if .Values.agent.managementCluster }}      
      - args: {{- toYaml .Values.classifierManager.manager.argsAgentMgmtCluster | nindent 8 }}
{{ else }}
      - args: {{- toYaml .Values.classifierManager.manager.args | nindent 8 }}
{{ end }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.classifierManager.manager.image.repository }}:{{ .Values.classifierManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.classifierManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.classifierManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: classifier-manager
      terminationGracePeriodSeconds: 10
---
{{ if .Values.agent.managementCluster }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sveltos-agent-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
{{ end }}
---
{{ if .Values.agent.managementCluster }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drift-detection-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
{{ end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shard-controller
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shard-controller
    app.kubernetes.io/part-of: shard-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard-controller
  labels:
    control-plane: shard-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.shardController.replicas }}
  selector:
    matchLabels:
      control-plane: shard-controller
    {{- include "projectsveltos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: shard-controller
      {{- include "projectsveltos.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.shardController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shardController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
{{ if .Values.agent.managementCluster }}
      - args: {{- toYaml .Values.shardController.manager.argsAgentMgmtCluster | nindent 8 }}
{{ else }}
      - args: {{- toYaml .Values.shardController.manager.args | nindent 8 }}
{{ end }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.shardController.manager.image.repository }}:{{ .Values.shardController.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.shardController.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.shardController.manager.containerSecurityContext
          | nindent 10 }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: shard-controller
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: register-mgmt-cluster
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-webhook
  labels:
    app: sveltos-webhook
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.conversionWebhook.replicas }}
  selector:
    matchLabels:
      app: sveltos-webhook
    {{- include "projectsveltos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sveltos-webhook
      {{- include "projectsveltos.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: sveltos-webhook
    spec:
      containers:
      - command:
        - /conversion-webhook
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.conversionWebhook.sveltosWebhook.image.repository }}:{{ .Values.conversionWebhook.sveltosWebhook.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: sveltos-webhook
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.conversionWebhook.sveltosWebhook.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.conversionWebhook.sveltosWebhook.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert

