{{ if .Values.agent.managementCluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drift-detection-metrics-reader
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{ end }}
