apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-eventtrigger-viewer-role
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
rules:
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - eventtriggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - eventtriggers/status
  verbs:
  - get