apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: projectsveltos-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/projectsveltos-serving-cert
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1alpha1
  clientConfig:
    service:
      name: 'webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-projectsveltos-v1beta1-clusterprofile
  failurePolicy: Fail
  name: mclusterprofile.projectsveltos.io
  sideEffects: None