apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: projectsveltos-serving-cert
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  dnsNames:
  - webhook-service.projectsveltos.svc
  - webhook-service.projectsveltos.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: 'project-selfsigned-issuer'
  secretName: webhook-server-cert
