apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shard-controller-rolebinding-extra
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'shard-controller-role-extra'
subjects:
- kind: ServiceAccount
  name: 'shard-controller'
  namespace: '{{ .Release.Namespace }}'