apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shard-controller-role-extra
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'