apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app: sveltos-webhook
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}