apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: wali-dev-1
  namespace: hmc-system
  labels:
    labelA: A
    labelB: B
    # labelC: C
spec:
  template: aws-standalone-cp-0-0-4
  credential: aws-cluster-identity-cred
  config:
    controlPlane:
      # amiID: ami-0eb9fdcf0d07bd5ef
      amiID: ami-0fd05997b4dff7aac #ap-south-1
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: true
    region: ap-south-1
    worker:
      amiID: ami-0fd05997b4dff7aac
      instanceType: t3.small
    workersNumber: 1
  services:
    # - template: kyverno-3-2-6
    #   name: kyverno
    #   namespace: kyverno
    - template: ingress-nginx-4-11-0
      name: ingress-nginx
      namespace: ingress-nginx
  servicesPriority: 1000
  stopOnConflict: false
