apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: aws-dev
  namespace: ${NAMESPACE}
spec:
  config:
    controlPlane:
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: true
    region: us-west-2
    worker:
      instanceType: t3.small
    workersNumber: 1
    installBeachHeadServices: false
  template: aws-standalone-cp
  services:
    - template: kyverno
      install: true # defaults to true
      releaseName: kyverno
      releaseNamespace: kyverno # defaults to releaseName
      createNamespace: true # defaults to true
      registryConfig:
        plainHTTP: true
    - template: ingress-nginx
      install: true
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      createNamespace: false
      values: |
        fullnameOverride: ingress-nginx
      registryConfig:
        plainHTTP: true
