apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: aws-dev
  namespace: ${NAMESPACE}
spec:
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: ${NAMESPACE}
    controlPlane:
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: true
    region: us-west-2
    worker:
      instanceType: t3.small
    workersNumber: 1
    installBeachHeadServices: false
  template: aws-standalone-cp-0-0-1
  priority: 100
  services:
    - template: kyverno-3-2-6
      name: kyverno
      namespace: kyverno
    - template: ingress-nginx-4-11-0
      name: ingress-nginx
      namespace: ingress-nginx
