apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: aws-dev
  namespace: ${NAMESPACE}
spec:
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: ${NAMESPACE}
    controlPlane:
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: true
    region: us-west-2
    worker:
      instanceType: t3.small
    workersNumber: 1
    installBeachHeadServices: false
  template: aws-standalone-cp
  services:
    - template: kyverno
      name: kyverno
      namespace: kyverno
    - template: ingress-nginx
      name: ingress-nginx
      namespace: ingress-nginx
