apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: wali-aws-dev
  namespace: ${NAMESPACE}
spec:
  config:
    controlPlane:
      amiID: ami-04e7552b5a2a47e47
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: true
    region: ca-central-1
    worker:
      amiID: ami-04e7552b5a2a47e47
      instanceType: t3.small
    workersNumber: 1
    installBeachHeadServices: false
  template: aws-standalone-cp
  services:
    - template: kyverno
      name: kyverno
      namespace: kyverno
    - template: ingress-nginx
      name: ingress-nginx
      namespace: ingress-nginx
