apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: ingress-nginx-4-11-3
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartName: ingress-nginx
    chartVersion: 4.11.3
